### ISSUE TITLE
SIGILL: illegal instruction

### ISSUE THREAD

**Issue by Jor-Tech** [flashbots/mev-boost#256]
Since version 0.7.10 I'm getting the following error when trying to run -help or -version..

```
SIGILL: illegal instruction
PC=0x6db7ae m=0 sigcode=2
signal arrived during cgo execution
instruction bytes: 0xf3 0x4c 0xf 0x38 0xf6 0xcf 0x66 0x4c 0xf 0x38 0xf6 0xd5 0xc4 0xe2 0xc3 0xf6

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x6bda00, 0xc00013dba8)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00013db80 sp=0xc00013db48 pc=0x4097bc
github.com/supranational/blst/bindings/go._Cfunc_blst_sk_to_pk2_in_g1(0x0, 0xc00012a240, 0xc000132ce0)
	_cgo_gotypes.go:1317 +0x45 fp=0xc00013dba8 sp=0xc00013db80 pc=0x66f7e5
github.com/supranational/blst/bindings/go.(*_Ctype_struct___4).From(...)
	/home/ethereum/go/pkg/mod/github.com/supranational/blst@v0.3.7/bindings/go/blst.go:219
github.com/flashbots/go-boost-utils/bls.PublicKeyFromSecretKey(...)
	/home/ethereum/go/pkg/mod/github.com/flashbots/go-boost-utils@v0.3.5/bls/bls.go:40
github.com/flashbots/mev-boost/server.init()
	/home/ethereum/go/pkg/mod/github.com/flashbots/mev-boost@v0.7.10/server/mock_relay.go:25 +0xec fp=0xc00013dbf0 sp=0xc00013dba8 pc=0x6bb1cc
runtime.doInit(0x990f40)
	/usr/local/go/src/runtime/proc.go:6222 +0x126 fp=0xc00013dd20 sp=0xc00013dbf0 pc=0x4491e6
runtime.doInit(0x98f000)
	/usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc00013de50 sp=0xc00013dd20 pc=0x449131
runtime.doInit(0x98a600)
	/usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc00013df80 sp=0xc00013de50 pc=0x449131
runtime.main()
	/usr/local/go/src/runtime/proc.go:233 +0x1d3 fp=0xc00013dfe0 sp=0xc00013df80 pc=0x43c373
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00013dfe8 sp=0xc00013dfe0 pc=0x468ac1

rax    0x0
rbx    0x7f9f20
rcx    0x7f99a0
rdx    0x7817fc679976fff5
rdi    0xc25f1572e1a87b0e
rsi    0x7f9ea0
rbp    0x2b7cd71362065849
rsp    0x7ffc88619968
r8     0x1f36a914d1d1ca54
r9     0xe3f09cc9f448ab2c
r10    0x53ae4ce3194e4adf
r11    0x988f6b1f351f9469
r12    0xf0030d9fa553ae92
r13    0x8e738258ad84f1f6
r14    0x685276af035ca2f
r15    0x0
rip    0x6db7ae
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0

```

I did not get this error with the previous two versions.
How can I resolve this problem?

**Comment by metachris** [comment]
I think it's because you need the portable BLST build. How do you install mev-boost? #258 should be a fix if you use Docker?

**Comment by Jor-Tech** [comment]
Tried both `go install` and `git pull` with both same result.
Are there other options then docker, I kinda like and run everything native with systemd.

(previous versions had no issues for me and would be great to have it working again with the `go install` option.

**Comment by metachris** [comment]
Which is the last version that you can install without this issue?

**Comment by Jor-Tech** [comment]
v0.7.9 works fine with `go install`

**Comment by metachris** [comment]
```CGO_CFLAGS=-"O -D__BLST_PORTABLE__" go install github.com/flashbots/mev-boost@latest``` should work

**Comment by Jor-Tech** [comment]
Thanks so much metachris, this works flawless!

Will keep this in store for when a normal go install won't work.

Looking forward for Mainnet Relay.

**Comment by metachris** [comment]
See also https://github.com/flashbots/mev-boost/pull/258

**Comment by metachris** [comment]
merged. will create a new tag soon to publish the portable docker images

**Comment by metachris** [comment]
@calamenium - i saw the linked PR and spotted an issue in it - left a comment on  https://github.com/remyroy/ethstaker/pull/32/files

**Comment by metachris** [comment]
portable images and build instructions are now live
