### ISSUE TITLE
Cannot start mev-boost

### ISSUE THREAD

**Issue by besu-p2p-host** [flashbots/mev-boost#318]
When I run "go version" it says go version go1.19.1 linux/amd64. But it seems to load 1.18.2?
Not sure if this is a go issue though!

```
sep 16 10:01:16 stakingserver systemd[1]: mev-boost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
sep 16 10:01:16 stakingserver systemd[1]: mev-boost.service: Failed with result 'exit-code'.
sep 16 10:01:22 stakingserver systemd[1]: mev-boost.service: Scheduled restart job, restart counter is at 145.
sep 16 10:01:22 stakingserver systemd[1]: Stopped MEV-Boost Relay.
sep 16 10:01:22 stakingserver systemd[1]: Started MEV-Boost Relay.
sep 16 10:01:22 stakingserver mev-boost[1049856]: SIGILL: illegal instruction
sep 16 10:01:22 stakingserver mev-boost[1049856]: PC=0x6dd361 m=0 sigcode=2
sep 16 10:01:22 stakingserver mev-boost[1049856]: signal arrived during cgo execution
sep 16 10:01:22 stakingserver mev-boost[1049856]: instruction bytes: 0xc4 0x62 0xbb 0xf6 0xca 0xe8 0x35 0xf8 0xff 0xff 0x4c 0x8b 0x7c 0x24 0x18 0x4c
sep 16 10:01:22 stakingserver mev-boost[1049856]: goroutine 1 [syscall, locked to thread]:
sep 16 10:01:22 stakingserver mev-boost[1049856]: runtime.cgocall(0x6bee40, 0xc000149ba8)
sep 16 10:01:22 stakingserver mev-boost[1049856]:         /usr/lib/go-1.18.2/src/runtime/cgocall.go:157 +0x5c fp=0xc000149b80 sp=0xc000149b48 pc=0x4097bc
sep 16 10:01:22 stakingserver mev-boost[1049856]: github.com/supranational/blst/bindings/go._Cfunc_blst_sk_to_pk2_in_g1(0x0, 0xc0001002a0, 0xc00013ece0)
sep 16 10:01:22 stakingserver mev-boost[1049856]:         _cgo_gotypes.go:1317 +0x45 fp=0xc000149ba8 sp=0xc000149b80 pc=0x66f665
sep 16 10:01:22 stakingserver mev-boost[1049856]: github.com/supranational/blst/bindings/go.(*_Ctype_struct___4).From(...)
sep 16 10:01:22 stakingserver mev-boost[1049856]:         /root/go/pkg/mod/github.com/supranational/blst@v0.3.7/bindings/go/blst.go:219
sep 16 10:01:22 stakingserver mev-boost[1049856]: github.com/flashbots/go-boost-utils/bls.PublicKeyFromSecretKey(...)
sep 16 10:01:22 stakingserver mev-boost[1049856]:         /root/go/pkg/mod/github.com/flashbots/go-boost-utils@v0.3.5/bls/bls.go:40
sep 16 10:01:22 stakingserver mev-boost[1049856]: github.com/flashbots/mev-boost/server.init()
sep 16 10:01:22 stakingserver mev-boost[1049856]:         /root/go/pkg/mod/github.com/flashbots/mev-boost@v1.2.1/server/mock_relay.go:25 +0xec fp=0xc000149bf0 sp=0xc000149ba8 pc=0x6bbf4c
sep 16 10:01:22 stakingserver mev-boost[1049856]: runtime.doInit(0x993f40)
sep 16 10:01:22 stakingserver mev-boost[1049856]:         /usr/lib/go-1.18.2/src/runtime/proc.go:6222 +0x126 fp=0xc000149d20 sp=0xc000149bf0 pc=0x4491e6
sep 16 10:01:22 stakingserver mev-boost[1049856]: runtime.doInit(0x992200)
sep 16 10:01:22 stakingserver mev-boost[1049856]:         /usr/lib/go-1.18.2/src/runtime/proc.go:6199 +0x71 fp=0xc000149e50 sp=0xc000149d20 pc=0x449131
sep 16 10:01:22 stakingserver mev-boost[1049856]: runtime.doInit(0x98d600)
sep 16 10:01:22 stakingserver mev-boost[1049856]:         /usr/lib/go-1.18.2/src/runtime/proc.go:6199 +0x71 fp=0xc000149f80 sp=0xc000149e50 pc=0x449131
sep 16 10:01:22 stakingserver mev-boost[1049856]: runtime.main()
sep 16 10:01:22 stakingserver mev-boost[1049856]:         /usr/lib/go-1.18.2/src/runtime/proc.go:233 +0x1d3 fp=0xc000149fe0 sp=0xc000149f80 pc=0x43c373
sep 16 10:01:22 stakingserver mev-boost[1049856]: runtime.goexit()
sep 16 10:01:22 stakingserver mev-boost[1049856]:         /usr/lib/go-1.18.2/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000149fe8 sp=0xc000149fe0 pc=0x468ac1
sep 16 10:01:22 stakingserver mev-boost[1049856]: rax    0x154f95c7143ba1c1
sep 16 10:01:22 stakingserver mev-boost[1049856]: rbx    0x7fbc80
sep 16 10:01:22 stakingserver mev-boost[1049856]: rcx    0x7fb700
sep 16 10:01:22 stakingserver mev-boost[1049856]: rdx    0x5cb38790fd530c16
sep 16 10:01:22 stakingserver mev-boost[1049856]: rdi    0xedce6ecc21dbf440
sep 16 10:01:22 stakingserver mev-boost[1049856]: rsi    0x7fbc00
sep 16 10:01:22 stakingserver mev-boost[1049856]: rbp    0x120177419e0bfb75
sep 16 10:01:22 stakingserver mev-boost[1049856]: rsp    0x7ffd336526d0
sep 16 10:01:22 stakingserver mev-boost[1049856]: r8     0x89f3fffcfffcfffd
sep 16 10:01:22 stakingserver mev-boost[1049856]: r9     0x0
sep 16 10:01:22 stakingserver mev-boost[1049856]: r10    0xe1be4219b1b95033
sep 16 10:01:22 stakingserver mev-boost[1049856]: r11    0x3d5516c22678a27f
sep 16 10:01:22 stakingserver mev-boost[1049856]: r12    0xf0ae6acdf3d0e747
sep 16 10:01:22 stakingserver mev-boost[1049856]: r13    0x7ffd33652900
sep 16 10:01:22 stakingserver mev-boost[1049856]: r14    0x7ffd33652730
sep 16 10:01:22 stakingserver mev-boost[1049856]: r15    0x7817fc679976fff5
sep 16 10:01:22 stakingserver mev-boost[1049856]: rip    0x6dd361
sep 16 10:01:22 stakingserver mev-boost[1049856]: rflags 0x10246
sep 16 10:01:22 stakingserver mev-boost[1049856]: cs     0x33
sep 16 10:01:22 stakingserver mev-boost[1049856]: fs     0x0
sep 16 10:01:22 stakingserver mev-boost[1049856]: gs     0x0
sep 16 10:01:22 stakingserver systemd[1]: mev-boost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
sep 16 10:01:22 stakingserver systemd[1]: mev-boost.service: Failed with result 'exit-code'.
```

**Comment by metachris** [comment]
you need to run or build the portable version. see https://github.com/flashbots/mev-boost#troubleshooting
