### ISSUE TITLE
Error in Teku: "Failed to send validator registrations to the builder network via the Beacon Node"

### ISSUE THREAD

**Issue by rene78** [flashbots/mev-boost#386]
Sorry in advance for this question, which might not be a problem of mev-boost at all.
I have set up mev-boost as explained on [Coincashew](https://www.coincashew.com/coins/overview-eth/mev-boost) and added the appropriate settings in the Teku service file. But Teku gives me this error message:

```
2022-10-24 14:49:23.006+00:00 | validator-async-7 | INFO  | ValidatorRegistrationBatchSender | 0 out of 1 validator(s) registrations were successfully sent to the builder network via the Beacon Node.
2022-10-24 13:49:35.003+00:00 | validator-async-10 | ERROR | teku-validator-log | Validator   *** Failed to send validator registrations to the builder network via the Beacon Node
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to register validators: builder not available
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
```

The journalctl from mev-boost looks clean:

```
Oct 24 14:45:19 renes-server systemd[1]: Started mev-boost ethereum mainnet.
Oct 24 14:45:19 renes-server mev-boost[301697]: time="2022-10-24T14:45:19Z" level=info msg="mev-boost v1.3.2" module=cli
Oct 24 14:45:19 renes-server mev-boost[301697]: time="2022-10-24T14:45:19Z" level=info msg="using genesis fork version: 0x00000000" module=cli
Oct 24 14:45:19 renes-server mev-boost[301697]: time="2022-10-24T14:45:19Z" level=info msg="using 3 relays" module=cli relays="[https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1eea11168503240ac35d101c9135@mainnet-relay.securerpc.com https://0xad0a8bb54565c2211cee576363f3a347089d2f07cf72679d16911d740262694cadb62d7fd7483f27afd714ca0f1b9118@bloxroute.ethical.blxrbdn.com https://0x8b5d2e73e2a3a55c6c87b8b6eb92e0149a125c852751db1422fa951e42a09b82c142c3ea98d0d9930b056a3bc9896b8f@bloxroute.max-profit.blxrbdn.com]"
Oct 24 14:45:20 renes-server mev-boost[301697]: time="2022-10-24T14:45:20Z" level=info msg="listening on localhost:18550" module=cli
```

Any idea what I could have done wrong? Thanks in advance for your time!

**Comment by rene78** [comment]
I had a syntax error in the Teku systemd service file (forgotten the backslashes at the end of the newly added configurations). Everything seems to be working now.
